In [178]:
import os
import pandas as pd

In [179]:
df = pd.read_csv('GoalscorerData.csv')

In [180]:
df.head()

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
0,Spain,La Liga,(BET),Juanmi Callejon,19,16,1849,11,6.62,0.34,48,20,2.47,1.03,2016
1,Spain,La Liga,(BAR),Antoine Griezmann,36,0,3129,16,11.86,0.36,88,41,2.67,1.24,2016
2,Spain,La Liga,(ATL),Luis Suarez,34,1,2940,28,23.21,0.75,120,57,3.88,1.84,2016
3,Spain,La Liga,(CAR),Ruben Castro,32,3,2842,13,14.06,0.47,117,42,3.91,1.40,2016
4,Spain,La Liga,(VAL),Kevin Gameiro,21,10,1745,13,10.65,0.58,50,23,2.72,1.25,2016

In [181]:
df.isnull().sum()

Country                    0
League                     0
Club                       0
Player Names               0
Matches_Played             0
Substitution               0
Mins                       0
Goals                      0
xG                         0
xG Per Avg Match           0
Shots                      0
OnTarget                   0
Shots Per Avg Match        0
On Target Per Avg Match    0
Year                       0
dtype: int64

In [182]:
df['Player Names'].value_counts()
df[df['Player Names'] == 'Ciro Immobile']

,Country,League,Club,Player Names,Matches_Played,Substitution,Mins,Goals,xG,xG Per Avg Match,Shots,OnTarget,Shots Per Avg Match,On Target Per Avg Match,Year
22,Italy,Serie A,(LAZ),Ciro Immobile,35,1,3294,22,19.76,0.57,136,98,3.92,2.83,2016
135,Italy,Serie A,(LAZ),Ciro Immobile,33,0,2799,29,19.15,0.65,110,53,3.73,1.80,2017
204,Italy,Serie A,(LAZ),Ciro Immobile,31,5,3046,15,15.71,0.49,124,49,3.87,1.53,2018
391,Italy,Serie A,(LAZ),Ciro Immobile,36,1,3371,36,26.61,0.75,142,71,4.00,2.00,2019
556,Italy,Serie A,(LAZ),Ciro Immobile,6,1,571,5,3.73,0.62,22,8,3.66,1.33,2020

In [183]:
df2 = df.set_index('Player Names').groupby('Player Names').mean()
print(df2.Goals)
goals = df2.Goals
%store goals

Player Names
Abdou Harroui           4.000000
Adrien Hunou            8.000000
Adrien Thomasson        7.000000
Aduriz                 16.000000
Alassane Plea          11.000000
                         ...
Yeferson Soteldo        9.000000
Youssef   En-Nesyri     4.000000
Yussuf Poulsen         15.000000
Zlatan Ibrahimovic     19.333333
Ãngel Di Maria         8.000000
Name: Goals, Length: 444, dtype: float64
Stored 'goals' (Series)

In [184]:
df3 = df.set_index('Player Names').groupby('Player Names').mean()
print(df2.Mins)
Minutes_Played = df2.Mins
%store Minutes_Played

Player Names
Abdou Harroui           834.000000
Adrien Hunou           1325.000000
Adrien Thomasson       2168.000000
Aduriz                 2480.000000
Alassane Plea          2432.500000
                          ...
Yeferson Soteldo       2883.000000
Youssef   En-Nesyri     465.000000
Yussuf Poulsen         2556.000000
Zlatan Ibrahimovic     2044.333333
Ãngel Di Maria        2106.000000
Name: Mins, Length: 444, dtype: float64
Stored 'Minutes_Played' (Series)